swagger: "2.0"
info:
  description: "Esse é um servidor de uma API que recebe os dados de uma ou várias pessoas de um aplicativo Android e imprime os dados em uma janela de terminal Unix."
  version: "1.0.0"
  title: "Cadastro de Pessoal"
  contact:
    name: "Amilton Junior"
    email: "amiltonjunior2007@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "127.0.0.1"
basePath: "/api"
tags:
- name: "api"
  description: "Envio dos dados da API"
schemes:
- "http"
paths:
  /:
    post:
      tags:
      - "/"
      summary: "Envia os dados das pessoas para o servidor e imprime no terminal Unix"
      description: ""
      operationId: "sendPerson"
      consumes:
      - "application/x-www-form-urlencoded"
      produces:
      - "application/json"
      parameters:
      - name: "name"
        in: "formData"
        description: "Nome da pessoa"
        required: true
        type: "string"
      - name: "age"
        in: "formData"
        description: "Idade da pessoa"
        required: true
        type: "integer"
      - name: "sex"
        in: "formData"
        description: "Sexo da pessoa"
        required: true
        type: "string"
      responses:
        200:
          description: "OK"
        405:
          description: "Entrada inválida"